databases:
  - name: black-swing-db
    databaseName: black_swing
    user: black_swing
    plan: free

services:
  - type: web
    name: black-swing
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn black_swing.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: black-swing-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

